name: scrapy101
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - appnope=0.1.4
  - asttokens=3.0.0
  - attrs=24.3.0
  - automat=24.8.1
  - bcrypt=4.3.0
  - beautifulsoup4=4.14.2
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - constantly=23.10.4
  - cryptography=44.0.1
  - cssselect=1.2.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.7.1
  - filelock=3.17.0
  - hyperlink=21.0.0
  - icu=73.1
  - idna=3.7
  - incremental=24.7.2
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - itemadapter=0.3.0
  - itemloaders=1.3.2
  - jedi=0.19.2
  - jmespath=1.0.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - libcxx=19.1.7
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libmpdec=4.0.0
  - libopenblas=0.3.29
  - libsodium=1.0.18
  - libxml2=2.13.8
  - libxslt=1.1.41
  - llvm-openmp=19.1.7
  - lxml=5.3.0
  - matplotlib-inline=0.1.6
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numexpr=2.11.0
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.1
  - parsel=1.8.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pip=25.2
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protego=0.4.0
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.21
  - pydispatcher=2.0.7
  - pygments=2.19.1
  - pyopenssl=25.0.0
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyzmq=26.2.0
  - queuelib=1.6.2
  - readline=8.3
  - requests=2.32.4
  - requests-file=2.1.0
  - scrapy=2.12.0
  - service_identity=24.2.0
  - setuptools=72.1.0
  - six=1.17.0
  - soupsieve=2.8
  - sqlite=3.50.2
  - stack_data=0.2.0
  - tk=8.6.15
  - tldextract=5.1.2
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - twisted=24.11.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.5.0
  - w3lib=2.1.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - zope=1.0
  - zope.interface=7.1.1
prefix: /Users/bbaror/miniconda3/envs/scrapy101
